import type { Brief, Profile } from "./types";

// Demo presets — used by the form for one-click profile loading.
export const demoProfiles: { id: string; label: string; profile: Profile }[] = [
  {
    id: "strong-cs",
    label: "Strong CS, top targets",
    profile: {
      name: "Aarav Mehta",
      intake: "Fall 2026",
      countries: ["US", "UK"],
      field: "Computer Science",
      degree: "Masters",
      gpa: 9.1,
      gpaScale: "10",
      greGmat: 328,
      ielts: 7.5,
      workExperienceYears: 2,
      budgetLakhs: 80,
    },
  },
  {
    id: "budget-ds",
    label: "Budget-constrained DS",
    profile: {
      name: "Priya Sharma",
      intake: "Fall 2026",
      countries: ["Canada", "Australia", "UK"],
      field: "Data Science",
      degree: "Masters",
      gpa: 8.2,
      gpaScale: "10",
      ielts: 7.0,
      workExperienceYears: 1,
      budgetLakhs: 35,
    },
  },
  {
    id: "mba-switcher",
    label: "MBA career switcher",
    profile: {
      name: "Rohan Kapoor",
      intake: "Fall 2026",
      countries: ["UK", "US"],
      field: "MBA",
      degree: "Masters",
      gpa: 7.8,
      gpaScale: "10",
      greGmat: 710,
      ielts: 7.5,
      workExperienceYears: 5,
      budgetLakhs: 75,
    },
  },
  {
    id: "weak-test",
    label: "Strong GPA, weak tests",
    profile: {
      name: "Sneha Iyer",
      intake: "Spring 2027",
      countries: ["US", "Canada"],
      field: "Business Analytics",
      degree: "Masters",
      gpa: 9.4,
      gpaScale: "10",
      greGmat: 305,
      ielts: 6.5,
      workExperienceYears: 0,
      budgetLakhs: 50,
    },
  },
  {
    id: "engineer-roi",
    label: "Engineer optimizing ROI",
    profile: {
      name: "Vikram Reddy",
      intake: "Fall 2026",
      countries: ["US", "Germany", "Australia"],
      field: "Engineering",
      degree: "Masters",
      gpa: 8.6,
      gpaScale: "10",
      greGmat: 318,
      ielts: 7.0,
      workExperienceYears: 3,
      budgetLakhs: 45,
    },
  },
];

// Used when ANTHROPIC_API_KEY is missing — keeps the UI demoable.
export function fixtureBrief(profile: Profile): Brief {
  return {
    studentName: profile.name || "Demo Student",
    generatedAt: new Date().toISOString(),
    profileSummary: `${profile.field} aspirant, GPA ${profile.gpa}/${profile.gpaScale}, ${profile.workExperienceYears}y work ex, IELTS ${profile.ielts}. (Fixture mode — set ANTHROPIC_API_KEY for live generation.)`,
    verdict:
      "Competitive for tier-2 US and tier-1 UK programs in field; tier-1 US remains a stretch without test score improvement.",
    recommendations: [
      {
        universityId: "cmu-mscs",
        name: "Carnegie Mellon University",
        country: "US",
        program: "MS in Computer Science",
        admitProbability: 0.09,
        visaApprovalRate: 0.86,
        employmentRateWithin6Mo: 0.96,
        medianStartingSalaryUsd: 145000,
        twoYearRoiPct: 127,
        totalCostInr: 10624000,
        fitBand: "Reach",
        rationale: "Profile below median admit; strong outcome if accepted.",
      },
      {
        universityId: "gatech-mscs",
        name: "Georgia Institute of Technology",
        country: "US",
        program: "MS in Computer Science",
        admitProbability: 0.28,
        visaApprovalRate: 0.88,
        employmentRateWithin6Mo: 0.93,
        medianStartingSalaryUsd: 128000,
        twoYearRoiPct: 198,
        totalCostInr: 7138000,
        fitBand: "Target",
        rationale: "GPA strong; visa rate solid; best ROI in tier-2 US set.",
      },
      {
        universityId: "imperial-mscs",
        name: "Imperial College London",
        country: "UK",
        program: "MSc Computing",
        admitProbability: 0.18,
        visaApprovalRate: 0.94,
        employmentRateWithin6Mo: 0.92,
        medianStartingSalaryUsd: 88000,
        twoYearRoiPct: 138,
        totalCostInr: 6142000,
        fitBand: "Reach",
        rationale: "Tier-1 UK; visa risk minimal; salary delta vs US notable.",
      },
      {
        universityId: "edinburgh-msds",
        name: "University of Edinburgh",
        country: "UK",
        program: "MSc Data Science",
        admitProbability: 0.36,
        visaApprovalRate: 0.93,
        employmentRateWithin6Mo: 0.87,
        medianStartingSalaryUsd: 72000,
        twoYearRoiPct: 157,
        totalCostInr: 4648000,
        fitBand: "Target",
        rationale: "Within budget, strong fit, lower employment ceiling.",
      },
      {
        universityId: "asu-msba",
        name: "Arizona State University",
        country: "US",
        program: "MS in Business Analytics",
        admitProbability: 0.55,
        visaApprovalRate: 0.9,
        employmentRateWithin6Mo: 0.88,
        medianStartingSalaryUsd: 92000,
        twoYearRoiPct: 136,
        totalCostInr: 6474000,
        fitBand: "Target",
        rationale: "Reliable safety; meaningful US OPT pathway.",
      },
      {
        universityId: "waterloo-mds",
        name: "University of Waterloo",
        country: "Canada",
        program: "MDS in Data Science",
        admitProbability: 0.32,
        visaApprovalRate: 0.76,
        employmentRateWithin6Mo: 0.91,
        medianStartingSalaryUsd: 92000,
        twoYearRoiPct: 217,
        totalCostInr: 4814000,
        fitBand: "Target",
        rationale: "Highest ROI in set; visa is the binding constraint.",
      },
      {
        universityId: "unsw-mscs",
        name: "University of New South Wales",
        country: "Australia",
        program: "MSc Computer Science",
        admitProbability: 0.48,
        visaApprovalRate: 0.91,
        employmentRateWithin6Mo: 0.86,
        medianStartingSalaryUsd: 78000,
        twoYearRoiPct: 73,
        totalCostInr: 7470000,
        fitBand: "Safety",
        rationale: "Comfortable admit; ROI compressed by high cost base.",
      },
    ],
    risks: [
      {
        severity: "high",
        title: "Visa approval rate for Canada has declined since 2024",
        detail:
          "Canadian study permit approvals for Indian applicants are at a 5-year low. Predicted approval at Toronto/Waterloo is 76% — model with a backup country.",
      },
      {
        severity: "medium",
        title: "Test score gates tier-1 US programs",
        detail:
          "GRE below 325 places this profile in the bottom quartile at CMU/MIT-class programs. A 10-point improvement raises admit probability by an estimated 8 percentage points.",
      },
      {
        severity: "low",
        title: "ROI compresses sharply at Australian programs",
        detail:
          "Tuition + living at UNSW/Melbourne consumes 70% of 2-year post-grad earnings. Consider only if PR pathway is the goal.",
      },
    ],
  };
}
