import type { UniversityRecord } from "./types";

// Hand-picked universities common in Indian-student target lists.
// Base rates are illustrative for a prototype, not real institutional stats.
// The LLM adjusts these per student profile.
export const universities: UniversityRecord[] = [
  // ── United States ──────────────────────────────────────────
  {
    id: "cmu-mscs",
    name: "Carnegie Mellon University",
    country: "US",
    city: "Pittsburgh",
    program: "MS in Computer Science",
    field: "Computer Science",
    degree: "Masters",
    baseAdmitRate: 0.08,
    baseVisaApprovalRate: 0.86,
    medianStartingSalaryUsd: 145000,
    employmentRateWithin6Mo: 0.96,
    tuitionUsd: 92000,
    livingCostUsd: 36000,
    tier: 1,
  },
  {
    id: "gatech-mscs",
    name: "Georgia Institute of Technology",
    country: "US",
    city: "Atlanta",
    program: "MS in Computer Science",
    field: "Computer Science",
    degree: "Masters",
    baseAdmitRate: 0.21,
    baseVisaApprovalRate: 0.88,
    medianStartingSalaryUsd: 128000,
    employmentRateWithin6Mo: 0.93,
    tuitionUsd: 58000,
    livingCostUsd: 28000,
    tier: 2,
  },
  {
    id: "nyu-msds",
    name: "New York University",
    country: "US",
    city: "New York",
    program: "MS in Data Science",
    field: "Data Science",
    degree: "Masters",
    baseAdmitRate: 0.18,
    baseVisaApprovalRate: 0.84,
    medianStartingSalaryUsd: 132000,
    employmentRateWithin6Mo: 0.91,
    tuitionUsd: 80000,
    livingCostUsd: 44000,
    tier: 1,
  },
  {
    id: "asu-msba",
    name: "Arizona State University",
    country: "US",
    city: "Tempe",
    program: "MS in Business Analytics",
    field: "Business Analytics",
    degree: "Masters",
    baseAdmitRate: 0.42,
    baseVisaApprovalRate: 0.9,
    medianStartingSalaryUsd: 92000,
    employmentRateWithin6Mo: 0.88,
    tuitionUsd: 54000,
    livingCostUsd: 24000,
    tier: 3,
  },
  {
    id: "northeastern-msie",
    name: "Northeastern University",
    country: "US",
    city: "Boston",
    program: "MS in Industrial Engineering",
    field: "Engineering",
    degree: "Masters",
    baseAdmitRate: 0.45,
    baseVisaApprovalRate: 0.87,
    medianStartingSalaryUsd: 98000,
    employmentRateWithin6Mo: 0.9,
    tuitionUsd: 62000,
    livingCostUsd: 34000,
    tier: 2,
  },

  // ── United Kingdom ─────────────────────────────────────────
  {
    id: "imperial-mscs",
    name: "Imperial College London",
    country: "UK",
    city: "London",
    program: "MSc Computing",
    field: "Computer Science",
    degree: "Masters",
    baseAdmitRate: 0.14,
    baseVisaApprovalRate: 0.94,
    medianStartingSalaryUsd: 88000,
    employmentRateWithin6Mo: 0.92,
    tuitionUsd: 48000,
    livingCostUsd: 26000,
    tier: 1,
  },
  {
    id: "edinburgh-msds",
    name: "University of Edinburgh",
    country: "UK",
    city: "Edinburgh",
    program: "MSc Data Science",
    field: "Data Science",
    degree: "Masters",
    baseAdmitRate: 0.28,
    baseVisaApprovalRate: 0.93,
    medianStartingSalaryUsd: 72000,
    employmentRateWithin6Mo: 0.87,
    tuitionUsd: 38000,
    livingCostUsd: 18000,
    tier: 2,
  },
  {
    id: "warwick-mba",
    name: "Warwick Business School",
    country: "UK",
    city: "Coventry",
    program: "Full-time MBA",
    field: "MBA",
    degree: "Masters",
    baseAdmitRate: 0.32,
    baseVisaApprovalRate: 0.92,
    medianStartingSalaryUsd: 110000,
    employmentRateWithin6Mo: 0.89,
    tuitionUsd: 62000,
    livingCostUsd: 22000,
    tier: 2,
  },

  // ── Canada ─────────────────────────────────────────────────
  {
    id: "toronto-mscs",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    program: "MSc Applied Computing",
    field: "Computer Science",
    degree: "Masters",
    baseAdmitRate: 0.16,
    baseVisaApprovalRate: 0.78,
    medianStartingSalaryUsd: 95000,
    employmentRateWithin6Mo: 0.9,
    tuitionUsd: 44000,
    livingCostUsd: 28000,
    tier: 1,
  },
  {
    id: "waterloo-mds",
    name: "University of Waterloo",
    country: "Canada",
    city: "Waterloo",
    program: "MDS in Data Science",
    field: "Data Science",
    degree: "Masters",
    baseAdmitRate: 0.22,
    baseVisaApprovalRate: 0.76,
    medianStartingSalaryUsd: 92000,
    employmentRateWithin6Mo: 0.91,
    tuitionUsd: 36000,
    livingCostUsd: 22000,
    tier: 2,
  },

  // ── Australia ──────────────────────────────────────────────
  {
    id: "unsw-mscs",
    name: "University of New South Wales",
    country: "Australia",
    city: "Sydney",
    program: "MSc Computer Science",
    field: "Computer Science",
    degree: "Masters",
    baseAdmitRate: 0.36,
    baseVisaApprovalRate: 0.91,
    medianStartingSalaryUsd: 78000,
    employmentRateWithin6Mo: 0.86,
    tuitionUsd: 58000,
    livingCostUsd: 32000,
    tier: 2,
  },
  {
    id: "melbourne-msba",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    program: "MS Business Analytics",
    field: "Business Analytics",
    degree: "Masters",
    baseAdmitRate: 0.3,
    baseVisaApprovalRate: 0.9,
    medianStartingSalaryUsd: 82000,
    employmentRateWithin6Mo: 0.85,
    tuitionUsd: 64000,
    livingCostUsd: 30000,
    tier: 1,
  },
];
